apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-app-config
  namespace: logging
  labels:
    app: fluent-bit
data:
  # Configuration files: server, input, filters and output
  # ======================================================
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    @INCLUDE input-kubernetes.conf
    @INCLUDE output-elasticsearch.conf

  input-kubernetes.conf: |
    [INPUT]
        name http
        host 0.0.0.0
        port 25678

  output-elasticsearch.conf: |
    [OUTPUT]
        Name                    es
        Match                   *
        Host                    10.140.0.33
        Port                    9200
        Logstash_Format         On
        Retry_Limit             False
        Trace_Error             On
        Time_Key                @timestamp
        Logstash_Prefix         applog

  parsers.conf: |
    [PARSER]
        Name   json
        Format json
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On

