apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: grafana-ssd
  namespace: monitoring
provisioner: kubernetes.io/gce-pd
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  type: pd-ssd
volumeBindingMode: WaitForFirstConsumer
