apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloweb
  namespace: logging
  labels:
    app: hello
spec:
  selector:
    matchLabels:
      app: hello
      tier: web
  replicas: 3
  template:
    metadata:
      labels:
        app: hello
        tier: web
    spec:
      containers:
      - name: hello-app
        image: sppo55/openresty:k8s
        ports:
        - containerPort: 80
        - containerPort: 443
