apiVersion: v1
kind: Service
metadata:
  name: openrestyweb
  namespace: openresty
  labels:
    app: openresty
spec:
  selector:
    app: openresty
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  type: LoadBalancer
  loadBalancerIP: 35.187.155.13
