apiVersion: v1
kind: Namespace
metadata:
  name: redis-cluster
  labels:
    app: redis
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-conf
  namespace: redis-cluster
  labels:
    app: redis
data:
  redis.conf: |
    appendonly yes
    cluster-enabled yes
    cluster-config-file /var/lib/redis/nodes.conf
    dir /var/lib/redis
    port 6379
